
const ATTACK_DATABASE = {
  "batter": {
    displayName: "Batter",
    bp: 33,
    hits: 3,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "beat": {
    displayName: "Beat",
    bp: 88,
    hits: 1,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "bite": {
    displayName: "Bite",
    bp: 67,
    hits: 1,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "bodyBash": {
    displayName: "Body Bash",
    bp: 57,
    hits: 1,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "boneCrusher": {
    displayName: "Bone Crusher",
    bp: 150,
    hits: 1,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "chomp": {
    displayName: "Chomp",
    bp: 99,
    hits: 1,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "clobber": {
    displayName: "Clobber",
    bp: 112,
    hits: 1,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "chomp": {
    displayName: "Chomp",
    bp: 99,
    hits: 1,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "doubleSlice": {
    displayName: "Double Slice",
    bp: 39,
    hits: 2,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "earthsplitter": {
    displayName: "Earthsplitter",
    bp: 142,
    hits: 1,
    targets: "single",
    element: "none",
    miss: 0.5,
  },
  "flatten": {
    displayName: "Flatten",
    bp: 66,
    hits: 1,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "flipKick": {
    displayName: "Flip Kick",
    bp: 90,
    hits: 1,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "fullswing": {
    displayName: "Fullswing",
    bp: 120,
    hits: 1,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "gunsBlazing": {
    displayName: "Guns Blazing",
    bp: 33,
    hits: 3,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "headbuster": {
    displayName: "Headbuster",
    bp: 195,
    hits: 1,
    targets: "single",
    element: "none",
    miss: 0.5,
  },
  "headbutt": {
    displayName: "Headbutt",
    bp: 121,
    hits: 1,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "headsmack": {
    displayName: "Headsmack",
    bp: 67,
    hits: 1,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "hit": {
    displayName: "Hit",
    bp: 45,
    hits: 1,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "kaboom": {
    displayName: "Kaboom!",
    bp: 110,
    hits: 1,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "kick": {
    displayName: "Kick",
    bp: 67,
    hits: 1,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "lightningSlash": {
    displayName: "Lightning Slash",
    bp: 44,
    hits: 3,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "maul": {
    displayName: "Maul",
    bp: 120,
    hits: 1,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "meteorPunch": {
    displayName: "Meteor Punch",
    bp: 30,
    hits: 3,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "nastyKick": {
    displayName: "Nasty Kick",
    bp: 150,
    hits: 1,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "ninjaStar": {
    displayName: "Ninja Star",
    bp: 90,
    hits: 1,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "oneTwoPunch": {
    displayName: "One-Two Punch",
    bp: 33,
    hits: 2,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "palmStrike": {
    displayName: "Palm Strike",
    bp: 90,
    hits: 1,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "peskyPoke": {
    displayName: "Pesky Poke",
    bp: 67,
    hits: 1,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "peskyPokes": {
    displayName: "Pesky Pokes",
    bp: 26,
    hits: 3,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "pinpointPierce": {
    displayName: "Pinpoint Pierce",
    bp: 66,
    hits: 1,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "pointyPokes": {
    displayName: "Pointy Pokes",
    bp: 26,
    hits: 3,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "powerPunch": {
    displayName: "Power Punch",
    bp: 110,
    hits: 1,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "practicedPunch": {
    displayName: "Practiced Punch",
    bp: 135,
    hits: 1,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "punch": {
    displayName: "Punch",
    bp: 67,
    hits: 1,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "rocketPunch": {
    displayName: "Rocket Punch",
    bp: 150,
    hits: 1,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "sharpClaws": {
    displayName: "Sharp Claws",
    bp: 52,
    hits: 2,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "shoot": {
    displayName: "Shoot",
    bp: 45,
    hits: 1,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "slap": {
    displayName: "Slap",
    bp: 45,
    hits: 1,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "slurp": {
    displayName: "Slurp",
    bp: 110,
    hits: 1,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "smackdown": {
    displayName: "Smackdown",
    bp: 44,
    hits: 2,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "sprayGun": {
    displayName: "Spray Gun",
    bp: 150,
    hits: 1,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "squish": {
    displayName: "Squish",
    bp: 45,
    hits: 1,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "stabStorm": {
    displayName: "Stab Storm",
    bp: 22,
    hits: 5,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "steamroll": {
    displayName: "Steamroll",
    bp: 90,
    hits: 1,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "steppingSlice": {
    displayName: "Stepping Slice",
    bp: 67,
    hits: 1,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "tackle": {
    displayName: "Tackle",
    bp: 90,
    hits: 1,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "tailSlap": {
    displayName: "Tail Slap",
    bp: 150,
    hits: 1,
    targets: "single",
    element: "none",
    miss: 0,
  },
  "ventilator": {
    displayName: "Ventilator",
    bp: 110,
    hits: 1,
    targets: "single",
    element: "none",
    miss: 0,
  },
}

