const ITEM_DATABASE = {
  "cursedSword": {
    displayName: "Cursed Sword",
    description: "+80 STR, -40 DEF",
    type: "stat",
    hp: 0,
    str: 80,
    spr: 0,
    def: -40,
    spd: 0,
    icon: "./images/teambuilder/items/Cursed_Sword.webp",
  },
  "cursedStaff": {
    displayName: "Cursed Staff",
    description: "+80 SPR, -40 SPD",
    type: "stat",
    hp: 0,
    str: 0,
    spr: 80,
    def: 0,
    spd: -40,
    icon: "./images/teambuilder/items/Cursed_Staff.webp",
  },
  "tenguFan": {
    displayName: "Tengu Fan",
    description: "+100SPR, +100 SPD (Tengu and Flengu ONLY!)",
    type: "stat",
    hp: 0,
    str: 0,
    spr: 100,
    def: 0,
    spd: 100,
    icon: "./images/teambuilder/items/Tengu_Fan.webp",
  },
  "beefyBell": {
    displayName: "Beefy Bell",
    description: "+50 STR (Nyan Yokai ONLY!)",
    type: "stat",
    hp: 0,
    str: 30,
    spr: 0,
    def: 0,
    spd: 0,
    icon: "./images/teambuilder/items/Beefy_Bell.webp",
  },
  "legendBracelet": {
    displayName: "Legend Bracelet",
    description: "+80 STR, -40 DEF",
    type: "stat",
    hp: 0,
    str: 80,
    spr: 0,
    def: -40,
    spd: 0,
    icon: "./images/teambuilder/items/Legend_Bracelet.webp",
  },
  "fiendRing": {
    displayName: "Fiend Ring",
    description: "+50 SPD, -25 DEF",
    type: "stat",
    hp: 0,
    str: 0,
    spr: 0,
    def: -25,
    spd: 50,
    icon: "./images/teambuilder/items/Fiend_Ring.webp",
  },
  "stingingSoul": {
    displayName: "Stinging Soul",
    description: "Make opponent yokai attack the holder. (Taunt)",
    type: "effect",
    icon: "./images/teambuilder/items/Stealth_Soul.webp",
  },
  "speedSoul": {
    displayName: "Speed Soul",
    description: "Holder moves first when switched in.",
    type: "effect",
    icon: "./images/teambuilder/items/Scatter_Soul.webp",
  },
  "stealthSoul": {
    displayName: "Stealth Soul",
    description: "Secrecy, holder will not be targeted with other active teammates.",
    type: "effect",
    icon: "./images/teambuilder/items/Stealth_Soul.webp",
  },
  "shieldingSoul": {
    displayName: "Shielding Soul",
    description: "Yokai will always guard when switched in.",
    type: "effect",
    icon: "./images/teambuilder/items/Stout_Soul.webp",
  },
  "supernaturalSoul": {
    displayName: "Supernatural Soul",
    description: "Inspirits always hit. (Does not apply if the inspirit is a secondary effect of a soultimate)",
    type: "effect",
    icon: "./images/teambuilder/items/Stealth_Soul.webp",
  },
  "ahSoul": {
    displayName: "Adjacent Healing Soul",
    description: "Heal the yokai on either side of the holder by 2% of their max HP.",
    type: "effect",
    icon: "./images/teambuilder/items/Heartful_Soul.webp",
  },
  "dragonSoul": {
    displayName: "Greesel/Robodraggie (GRD) Soul",
    description: "Multiplies soultimate damage by 1.5x. Holding two: 2x",
    type: "effect",
    icon: "./images/teambuilder/items/Slippery_Soul.webp",
  },
  "1hpSoul": {
    displayName: "1HP Soul",
    description: "Survive a hit that would've knocked you out with 1hp. Only works once.",
    type: "effect",
    icon: "./images/teambuilder/items/Tough_Soul.webp",
  },
  "smogSoul": {
    displayName: "Smogmella Soul",
    description: "Slowly charge the soul meters of yokai on either side of the holder.",
    type: "effect",
    icon: "./images/teambuilder/items/Mysterious_Soul.webp",
  },
  "devSoul": {
    displayName: "Devourer Soul",
    description: "Increase crit chance.",
    type: "effect",
    icon: "./images/teambuilder/items/Brave_Soul.webp",
  },
  "houSoul": {
    displayName: "Houzzat Soul",
    description: "Increase the SPR of yokai on either side of the holder by 20%",
    type: "effect",
    icon: "./images/teambuilder/items/Mysterious_Soul.webp",
  },
  "nyanSoul": {
    displayName: "Rubinyan Soul",
    description: "Increase the STR of yokai on either side of the holder by 20%",
    type: "effect",
    icon: "./images/teambuilder/items/Charming_Soul.webp",
  },
  "robofSoul": {
    displayName: "Robo-F Soul",
    description: "When the holder guards, return 150% of received physical damage.",
    type: "effect",
    icon: "./images/teambuilder/items/Tough_Soul.webp",
  },
}