const SOULTIMATE_DATABASE = {
  "bonitoBlade": {
    displayName: "Bonito Blade",
    bp: 25,
    hits: 10,
    targets: "allEnemies",
    attribute: "none",
    type: "damage",
    inspirit: "none",
    video: "./videos/battle/soultimateVideos/bonitoBlade.mp4",
    videoMoxie: "./videos/battle/soultimateVideos/bonitoBladeMoxie.mp4"
  },
  "boohooBlast": {
    displayName: "BooHoo Blast",
    bp: 30,
    hits: 1,
    targets: "allEnemies",
    attribute: "none",
    type: "damage",
    inspirit: "speedDown",
    video: "./videos/battle/soultimateVideos/boohooBlast.mp4",
    videoMoxie: "./videos/battle/soultimateVideos/boohooBlastMoxie.mp4"
  },
  "wartsAndAll": {
    displayName: "Warts and All",
    bp: 46,
    hits: 5,
    targets: "allEnemies",
    attribute: "none",
    type: "damage",
    inspirit: "none",
    video: "./videos/battle/soultimateVideos/wartsAndAll.mp4",
    videoMoxie: "./videos/battle/soultimateVideos/wartsAndAllMoxie.mp4"
  },
  "arcticAbyss": {
    displayName: "Arctic Abyss",
    bp: 250,
    hits: 1,
    targets: "allEnemies",
    attribute: "ice",
    type: "damage",
    inspirit: "none",
    video: "./videos/battle/soultimateVideos/arcticAbyss.mp4",
    videoMoxie: "./videos/battle/soultimateVideos/arcticAbyssMoxie.mp4"
  },
  "fullBloom": {
    displayName: "Full Bloom",
    bp: 100,
    hits: 1,
    targets: "allAllies",
    attribute: "none",
    type: "heal",
    inspirit: "none",
    video: "./videos/battle/soultimateVideos/______.mp4",
    videoMoxie: "./videos/battle/soultimateVideos/______.mp4",
  },
  "tigerMeow": {
    displayName: "Tiger Meow",
    bp: 285,
    hits: 1,
    targets: "singleEnemy",
    attribute: "none",
    type: "damage",
    inspirit: "none",
    video: "./videos/battle/soultimateVideos/______.mp4",
    videoMoxie: "./videos/battle/soultimateVideos/______.mp4",
  },
  "ignoranceIsBliss": {
    displayName: "Ignorance is Bliss",
    bp: 0,
    hits: 1,
    targets: "singleAlly",
    attribute: "none",
    type: "inspirit",
    inspirit: "speedUp",
    video: "./videos/battle/soultimateVideos/______.mp4",
    videoMoxie: "./videos/battle/soultimateVideos/______.mp4",
  },
  "uhErHoldOn": {
    displayName: "Uh, Er... Hold On",
    bp: 100,
    hits: 1,
    targets: "allEnemies",
    attribute: "none",
    type: "damage",
    inspirit: "loaf2",
    video: "./videos/battle/soultimateVideos/______.mp4",
    videoMoxie: "./videos/battle/soultimateVideos/______.mp4",
  },
  "centurEyeStare": {
    displayName: "Centur-Eye Stare",
    bp: 37,
    hits: 5,
    targets: "allEnemies",
    attribute: "none",
    type: "damage",
    inspirit: "none",
    video: "./videos/battle/soultimateVideos/______.mp4",
    videoMoxie: "./videos/battle/soultimateVideos/______.mp4",
  },
  "twistNTangle": {
    displayName: "Twist'N'Tangle",
    bp: 100,
    hits: 1,
    targets: "singleEnemy",
    attribute: "none",
    type: "damage",
    inspirit: "none",
    video: "./videos/battle/soultimateVideos/______.mp4",
    videoMoxie: "./videos/battle/soultimateVideos/______.mp4",
  },
  "stonewallDrop": {
    displayName: "Stonewall Drop",
    bp: 180,
    hits: 1,
    targets: "allEnemies",
    attribute: "earth",
    type: "damage",
    inspirit: "none",
    video: "./videos/battle/soultimateVideos/______.mp4",
    videoMoxie: "./videos/battle/soultimateVideos/______.mp4",
  },
  "scaryWrinkles": {
    displayName: "Scary Wrinkles",
    bp: 150,
    hits: 1,
    targets: "allEnemies",
    attribute: "none",
    type: "drain",
    inspirit: "none",
    video: "./videos/battle/soultimateVideos/______.mp4",
    videoMoxie: "./videos/battle/soultimateVideos/______.mp4",
  },
  "lickEmGood": {
    displayName: "Lick Em' Good!",
    bp: 32,
    hits: 8,
    targets: "allEnemies",
    attribute: "none",
    type: "damage",
    inspirit: "none",
    video: "./videos/battle/soultimateVideos/______.mp4",
    videoMoxie: "./videos/battle/soultimateVideos/______.mp4",
  },
  "blankFace": {
    displayName: "Blank Face",
    bp: 170,
    hits: 1,
    targets: "allEnemies",
    attribute: "none",
    type: "damage",
    inspirit: "none",
    video: "./videos/battle/soultimateVideos/______.mp4",
    videoMoxie: "./videos/battle/soultimateVideos/______.mp4",
  },
  "nightmareBeat": {
    displayName: "Nightmare Beat",
    bp: 350,
    hits: 1,
    targets: "singleEnemy",
    attribute: "none",
    type: "damage",
    inspirit: "none",
    video: "./videos/battle/soultimateVideos/______.mp4",
    videoMoxie: "./videos/battle/soultimateVideos/______.mp4",
  },
  "unpleasantKurse": {
    displayName: "Unpleasant Kurse",
    bp: 180,
    hits: 1,
    targets: "allEnemies",
    attribute: "none",
    type: "damage",
    inspirit: "none",
    video: "./videos/battle/soultimateVideos/______.mp4",
    videoMoxie: "./videos/battle/soultimateVideos/______.mp4",
  },
  "umbrellicade": {
    displayName: "Umbrellicade",
    bp: 0,
    hits: 1,
    targets: "self",
    attribute: "none",
    type: "inspirit",
    inspirit: "defUpTaunt",
    video: "./videos/battle/soultimateVideos/______.mp4",
    videoMoxie: "./videos/battle/soultimateVideos/______.mp4",
  },
  "pawsOfFury": {
    displayName: "Paws of Fury",
    bp: 20,
    hits: 5,
    targets: "allEnemies",
    attribute: "none",
    type: "damage",
    inspirit: "none",
    video: "./videos/battle/soultimateVideos/______.mp4",
    videoMoxie: "./videos/battle/soultimateVideos/______.mp4",
  },
}

module.exports = SOULTIMATE_DATABASE