const TECHNIQUE_DATABASE = {
  "torrent": {
    displayName: "Torrent",
    bp: 90,
    hits: 1,
    targets: "single",
    attribute: "water",
    type: "damage"
  },
  "rapids": {
    displayName: "Rapids",
    bp: 110,
    hits: 1,
    targets: "single",
    attribute: "water",
    type: "damage"
  },
  "waterfall": {
    displayName: "Waterfall",
    bp: 120,
    hits: 1,
    targets: "single",
    attribute: "water",
    type: "damage",
  },
  "pebble": {
    displayName: "Pebble",
    bp: 90,
    hits: 1,
    targets: "single",
    attribute: "earth",
    type: "damage"
  },
  "rockslide": {
    displayName: "Rockslide",
    bp: 110,
    hits: 1,
    targets: "single",
    attribute: "earth",
    type: "damage"
  },
  "meteor": {
    displayName: "Meteor",
    bp: 120,
    hits: 1,
    targets: "single",
    attribute: "earth",
    type: "damage"
  },
  "fire": {
    displayName: "Fire",
    bp: 90,
    hits: 1,
    targets: "single",
    attribute: "fire",
    type: "damage"
  },
  "blaze": {
    displayName: "Blaze",
    bp: 110,
    hits: 1,
    targets: "single",
    attribute: "fire",
    type: "damage"
  },
  "incinerate": {
    displayName: "Incinerate",
    bp: 120,
    hits: 1,
    targets: "single",
    attribute: "fire",
    type: "damage"
  },
  "whirlwind": {
    displayName: "Whirlwind",
    bp: 90,
    hits: 1,
    targets: "single",
    attribute: "wind",
    type: "damage",
  },
  "tornado": {
    displayName: "Tornado",
    bp: 110,
    hits: 1,
    targets: "single",
    attribute: "wind",
    type: "damage"
  },
  "storm": {
    displayName: "Storm",
    bp: 120,
    hits: 1,
    targets: "single",
    attribute: "wind",
    type: "damage"
  },
  "hail": {
    displayName: "Hail",
    bp: 90,
    hits: 1,
    targets: "single",
    attribute: "ice",
    type: "damage",
  },
  "frost": {
    displayName: "Frost",
    bp: 110,
    hits: 1,
    targets: "single",
    attribute: "ice",
    type: "damage",
  },
  "blizzard": {
    displayName: "Blizzard",
    bp: 120,
    hits: 1,
    targets: "single",
    attribute: "ice",
    type: "damage",
  },
  "shock": {
    displayName: "Shock",
    bp: 90,
    hits: 1,
    targets: "single",
    attribute: "lightning",
    type: "damage",
  },
  "lightning": {
    displayName: "Lightning",
    bp: 110,
    hits: 1,
    targets: "single",
    attribute: "lightning",
    type: "damage",
  },
  "voltage": {
    displayName: "Voltage",
    bp: 120,
    hits: 1,
    targets: "single",
    attribute: "lightning",
    type: "damage",
  },
  "absorb": {
    displayName: "Absorb",
    bp: 90,
    hits: 1,
    targets: "single",
    attribute: "drain",
    type: "drain",
  },
  "drain": {
    displayName: "Drain",
    bp: 110,
    hits: 1,
    targets: "single",
    attribute: "drain",
    type: "drain",
  },
  "reaper": {
    displayName: "Reaper",
    bp: 120,
    hits: 1,
    targets: "single",
    attribute: "drain",
    type: "drain",
  },
  "heal": {
    displayName: "Heal",
    bp: 90,
    hits: 1,
    targets: "party",
    attribute: "restoration",
    type: "heal",
  },
  "restore": {
    displayName: "Restore",
    bp: 110,
    hits: 1,
    targets: "party",
    attribute: "restoration",
    type: "heal",
  },
  "paradise": {
    displayName: "Paradise",
    bp: 120,
    hits: 1,
    targets: "party",
    attribute: "restoration",
    type: "heal",
  },
}

module.exports = TECHNIQUE_DATABASE